Update translation_hu.xml
Courseplay/Courseplay_FS22 pull request #2797
Opened 2023-09-23 13:28 UTC by RedMonster-HUN

Translation updated from line 447 to 560

2023-09-25 17:44 UTC, pvaiko requested changes
Köszönjük a fordítást, van néhány apró megjegyzésem hozzá.

2023-09-25 17:44 UTC, pvaiko commented on translations/translation_hu.xml
> +- Mező közepe: Különböző módok vannak arra, hogy miként nézzen ki a mező középső mintázata. A klassikus és legtöbbet használt opció az fel/le.
klasszikus

2023-09-25 17:44 UTC, pvaiko commented on translations/translation_hu.xml
> +- Sorok blokkonként: Ennek csak akkor van hatása, ha a mező közepe blokkokar van állítva és megmondja a generátornak, hogy hány sor legyen egy blokkban. Ha több a sor, kevesebb blokk lesz generálva.
blokkokra

2023-09-25 17:44 UTC, pvaiko commented on translations/translation_hu.xml
> +- Fordulósávok száma: A legjobb módja annak, hogy a gépeidet a mezőn tartsd, miközben a sorok végén megfordulnak az, ha fordulósávokat adsz az útvonalhoz.
Már akartam a múltkor is kérdezni, hogy a "mező" tényleg a jó fordítás-e a "field"-re. Én nem vagyok járatos a szakmában, de ha például mezőgazdasági GPS rendszerek magyar leírását, meg katalógusokat nézek, ott mindenhol a táblát használják.

2023-09-25 17:44 UTC, pvaiko commented on translations/translation_hu.xml
> +Az útvonalfájlok mentési helye: ..\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay\Courses\Mapname.SampleModMap (or for vanilla e.g. MapUS).
..\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay\Courses\<a térkép neve> (például MapUS az alapjátékban).

2023-09-25 17:44 UTC, pvaiko commented on translations/translation_hu.xml
> +- Munka kezdés helye: Ahogy említésre kerül a bővített AI menüben, a mező pozíciója arra szolgál, hogy a mezőmunka utvonal kezdetét vagy végét megadjuk.
Ahogy a bővitett AI menüben is láttuk vagy valami ilyesmi inkább, a kerül az nekem nagyon hivatalos.

2023-09-25 17:44 UTC, pvaiko commented on translations/translation_hu.xml
> +    <text name="CP_help_subTitle" text="Egy módosítás Farming Simulator 22 játékhoz"/>
Simán csak mod nem jobb?

2023-09-26 16:09 UTC, RedMonster-HUN commented on translations/translation_hu.xml
> +    <text name="CP_help_subTitle" text="Egy módosítás Farming Simulator 22 játékhoz"/>
Talán, de az eredetihez minnél közelebbi fordítást akartam.

2023-09-26 16:25 UTC, RedMonster-HUN commented
Elvégeztem a kért javításokat, valamint a mező>>tábla átírást számos helyen, egészen az eddig lefordított szakasz végéig.

2023-09-27 16:14 UTC, pvaiko approved these changes
Köszönjük a fordítást!

2023-09-27 16:14 UTC, merged