Improving how earth fruit harvesters are recognized
Courseplay/Courseplay_FS22 pull request #3022
Opened 2023-12-19 22:01 UTC by tn4799

Removed the old implementation with hardcoded fruit type checks. how searches all earth fruits and checks if at least one of them is supported. 

A earth fruit is defined by having a preparation entry in the xml file. The only exception to this definition is Sugarcane since it needs fruit preparing but is logially no earth fruit. This condition is checked in the seach.

Improvments of this PR:
- More Future proof and dynamically recognizion of earth fruits as long as giants sticks with fruit preparation
- now the self driving harvester of dewulf does turn properly

Things that still could be improved:
- Make chopper wait before turning to unload completly. This could be done to make turning a smooth movement without the unloader driving under the pipe all the time

2023-12-20 12:31 UTC, pvaiko requested changes
I think this is a good temporary improvement.

On the long term, as we discussed with @schwiti6190 , it is not really the fruit being harvested that determines the type of turn, it is rather the vehicle properties, like length, turning radius, working width etc., which makes the crop harvester type turns useless.

2023-12-20 12:31 UTC, pvaiko commented on scripts/ai/controllers/CombineController.lua
> +        self:debug(string.format("check if fruitType %s is supported", g_fillTypeManager:getFillTypeNameByIndex(fillUnitIndex)))
No need for the string.format(), debug() accepts format strings and arguments.

2023-12-20 12:31 UTC, pvaiko commented on scripts/CpUtil.lua
> +function CpUtil.getAllEarthFruits()
Can we call it root vegetable instead of earth fruit? Earth fruit is not used in English.

2023-12-20 14:54 UTC, pvaiko commented on scripts/CpUtil.lua
> +function CpUtil.getAllEarthFruits()
Also replacing all other occurrences of earth fruit?

2023-12-22 18:34 UTC, schwiti6190 approved these changes

2023-12-27 18:45 UTC, merged