fix: Hungarian translation
Courseplay/Courseplay_FS22 pull request #3138
Opened 2024-03-13 15:34 UTC by KallosLaszlo

Corrections and additions to the Hungarian translation

Also includes the latest chopper patch. (According to the old description, it was not supported.)

2024-03-19 19:05 UTC, pvaiko requested changes
Thanks for the translation, we really appreciate it, especially the help texts. I have a few comments, mainly regarding typos and consistent language. 

Thank you

2024-03-19 19:05 UTC, pvaiko commented on translations/translation_hu.xml
> +- Használja a HUD Cél ikonját a betakarított tábla kiválasztásához. A kirakodó kirakja az összes Courseplay hajtott betakarítógépet, amely azon a területen dolgozik.
Courseplay segítő által vezetett

2024-03-19 19:05 UTC, pvaiko commented on translations/translation_hu.xml
> +- A kirakodó elindításához a pályán vagy a pálya 20 méteres körzetében kell lennie.
a táblán, vagy annak 20 méteres körzetében

2024-03-19 19:05 UTC, pvaiko commented on translations/translation_hu.xml
> +Az, hogy ne várjon egy kombájnra, ha a pótkocsi majdnem tele van.
Ez Az,?

2024-03-19 19:05 UTC, pvaiko commented on translations/translation_hu.xml
> +    <text name="CP_help_page_unloaderTrailer_title" text="Utánfutók használata"/>
Pótkocsi jobban hangzik, legyen mindenhol az

2024-03-19 19:05 UTC, pvaiko commented on translations/translation_hu.xml
> +Utóbbi esetben a kerék ikon kékre váltásd, után kell kiválasztani a kirakodó állomást.
elgépelések

2024-03-19 19:05 UTC, pvaiko commented on translations/translation_hu.xml
> +A kirakodó elindításához helyezze vissza az útvonalra vagy 20 méteren belülre.
a táblára vagy annak 20 méteres körzetébe

2024-03-19 21:23 UTC, KallosLaszlo commented
I really appreciate you taking the time to check it. I'll review the translation again and make the necessary corrections along with your suggestions.

2024-03-19 21:26 UTC, KallosLaszlo commented
@pvaiko 
I have two questions. What Hungarian translation would you provide for the terms 'Giants helper' and 'multitool'?

2024-03-20 05:56 UTC, pvaiko commented
> @pvaiko I have two questions. What Hungarian translation would you provide for the terms 'Giants helper' and 'multitool'?

Beépített segítő? Normál segítő? Don't really have a good idea for multitool either. Többgépes?

2024-03-22 11:11 UTC, pvaiko commented
Are you still working on this, or just forgot to mark it ready for review?

2024-03-22 14:24 UTC, KallosLaszlo commented
> Are you still working on this, or just forgot to mark it ready for review?

I will finish the work this weekend.

2024-03-28 10:39 UTC, merged