Hud helpmenu remake
Courseplay/Courseplay_FS22 pull request #3208
Opened 2024-04-22 16:33 UTC by Tensuko

2024-04-22 16:50 UTC, pvaiko approved these changes

2024-04-23 19:50 UTC, schwiti6190 requested changes
The review is not completly finished yet ..

2024-04-24 18:10 UTC, schwiti6190 requested changes

2024-04-24 18:10 UTC, schwiti6190 commented on config/MasterTranslations.xml
> +A: Ballen die seit dem letzten scan (dies passiert automatisch) noch auf dem Feld liegen.
Ballen die nach dem letzten automatischen Scan noch auf dem Feld liegen.

2024-04-24 18:10 UTC, schwiti6190 commented on config/MasterTranslations.xml
> +A: Die Liter die noch auf dem gewählten Haufen erkannt werden.
Die aktuelle Füllmenge des gewählten Haufens.

2024-04-24 18:10 UTC, schwiti6190 commented on config/MasterTranslations.xml
> +B: Arbeitsbreite des Gerätes, gleich wie Feldarbeit.
Arbeitsbreite des Laders oder der Schaufel genauso wie bei der Feldarbeit.

2024-04-24 18:10 UTC, schwiti6190 commented on config/MasterTranslations.xml
> +C: Die höhe der Schaufel über den Boden ist ein Wert der relativ genau sein muss. Da dieser sich von Tool zu Tool unterscheiden kann, kannst du mit der Einstellung die höhe Live überprüfen und anpass
Offset für die Ladehöhe einer Schaufel. Dieser kann genutzt werden falls die Schaufel nicht tief genug gesenkt wird beim oder noch schlimmer sogar zu tief gesenkt wird.

2024-04-24 18:10 UTC, schwiti6190 commented on config/MasterTranslations.xml
> +D: Wie schon beim Abfahrer, kannst du heir die benötigten Marker kopieren und auf ein weiteres Gerät einfügen.
hier

2024-04-27 17:14 UTC, merged