WIP Changelog ModHub Update
Courseplay/Courseplay_FS22 pull request #3447
Opened 2024-09-21 13:30 UTC by Tensuko

2024-09-21 16:48 UTC, Rindula commented on modDesc.xml
> +- Schauelposition ist jetzt leicht nach unten gekippt und kann feiner eingestellt werden. (0.05er Schritte). Sollte dabei helfen einige silage silos besser zu entleeren.
```suggestion
- Schaufelposition ist jetzt leicht nach unten gekippt und kann feiner eingestellt werden. (0.05er Schritte). Sollte dabei helfen einige silage silos besser zu entleeren.
```

2024-09-21 16:59 UTC, Tritura2 commented on modDesc.xml
> +- Kurse auf der KI Karte zeigen jetzt kleine Pfeile um die Richtung der Bahnen anzuzeigen.
Pfeile, um

(ggf.: KI-Karte)

2024-09-21 16:59 UTC, Tritura2 commented on modDesc.xml
> +- Schauelposition ist jetzt leicht nach unten gekippt und kann feiner eingestellt werden. (0.05er Schritte). Sollte dabei helfen einige silage silos besser zu entleeren.
helfen, einge
Silagesilos

2024-09-21 16:59 UTC, Tritura2 commented on modDesc.xml
> +- Linienvorschau beim zeichnen eines eigenen Feldes und mit gedrückter linker shift taste lassen sich gerade linien ziehen.
Zeichnen
Shift-Taste
Linien

2024-09-21 16:59 UTC, Tritura2 commented on modDesc.xml
> +- Häcksler können wieder abgetankt werden, wie man es aus FS19 kennt. (Das vorzeitige rufen von einem 2ten Abfahrer ist nicht verfügbar).
Rufen

2024-09-21 16:59 UTC, Tritura2 commented on modDesc.xml
> +- Multitool Kurse beinhalten jetzt 2-5 einzelne Kurse für jede Bahn, abhänging von der Anzahl Fahrzeuge die gewählt wurden.
Fahrzeuge, die

2024-09-21 18:11 UTC, Tensuko commented
Danke fürs drüber gucken :) Ändere ich später.

2024-09-21 18:55 UTC, Tensuko commented on modDesc.xml
> +- Multitool Kurse beinhalten jetzt 2-5 einzelne Kurse für jede Bahn, abhänging von der Anzahl Fahrzeuge die gewählt wurden.
Das Komma wäre falsch, es ist kein eingeschobener Nebensatz.
Ansonsten wäre es "Multitool Kurse beinhalten jetzt 2-5 einzelne Kurse für jede Bahn die gewählt wurden."

2024-09-22 04:46 UTC, Tritura2 commented on modDesc.xml
> +- Kurse auf der KI Karte zeigen jetzt kleine Pfeile um die Richtung der Bahnen anzuzeigen.
Das Komma an dieser stelle fehlt aber auf jeden Fall. ^^

Man könnte zudem das erste "zeigen" durch "haben" oder "besitzen" ersetzen, um nicht zweimal "zeigen" in einem Satz zu verwenden.

2024-09-22 04:46 UTC, Tritura2 commented on modDesc.xml
> +- Linienvorschau beim Zeichnen eines eigenen Feldes und mit gedrückter linker Shift-Taste lassen sich gerade linien ziehen.
gerade **L**inien

2024-09-22 05:12 UTC, Tritura2 commented on modDesc.xml
> +- Added chopper unloader support known from FS19 back in.
Weil es in der deutschen Version steht:

(Premature calling of a second unloader is not available.)

Oder "Early calling"

2024-09-22 10:19 UTC, Tensuko commented
Na jetzt habe ich hoffentlich alles :) Danke auf jeden Fall.

2024-10-05 22:45 UTC, pvaiko commented
* Multitool courses generated with previous releases won't work, you must regenerate them with this release.
* Although non-multitool courses saved with previous releases will work, we recommend to regenerate them for best results.

2024-10-06 06:18 UTC, Tritura2 commented
You should consider to add your warning from CP-Version 7.4.2.0:

WARNING: while this version is backwards compatible with older savegames, it'll write the courses to the savegame in a new format. Older versions WILL NOT BE ABLE TO READ the games saved with this version! If you install this version, and decide to revert to an old one, YOU MUST BACK UP YOUR OLD SAVEGAME before!

2024-10-06 11:59 UTC, Tensuko commented
Added the warning, however, there is a 2nd solution to start the game without CP, save it, load it again with CP, but ofc vehicle settings and stuff is getting lost...

2024-10-20 12:23 UTC, pvaiko requested changes

2024-10-20 12:23 UTC, pvaiko commented on modDesc.xml
>  - More bugxies.
bugxie?

2024-10-26 15:09 UTC, merged